# Generated by Django 4.2.29 on 2026-03-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_emailverificationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('allocated', 'Allocated Funds'), ('income', 'Income')], max_length=10),
        ),
    ]
