# Generated by Django 4.2.29 on 2026-05-06 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('restaurants', 'Restaurants & Dining'), ('drinks', 'Drinks & Beverages'), ('transport', 'Transport & Fuel'), ('vehicle', 'Vehicle Maintenance'), ('public_transport', 'Public Transport'), ('parking', 'Parking & Tolls'), ('rent', 'Rent'), ('mortgage', 'Mortgage'), ('home_maintenance', 'Home Maintenance'), ('home_decor', 'Home Decor & Furniture'), ('electricity', 'Electricity'), ('water', 'Water'), ('internet', 'Internet Cable'), ('phone', 'Phone & Data'), ('health', 'Health & Medical'), ('pharmacy', 'Pharmacy & Medicine'), ('gym', 'Gym & Fitness'), ('haircut', 'Haircuts & Grooming'), ('skincare', 'Skincare & Beauty'), ('tuition', 'School Fees & Tuition'), ('courses', 'Courses & Certifications'), ('books', 'Books & Stationery'), ('workshops', 'Workshops & Training'), ('clothing', 'Clothing & Shoes'), ('gadgets', 'Gadgets & Electronics'), ('shopping', 'General Shopping'), ('entertainment', 'Entertainment & Leisure'), ('streaming', 'Streaming & Subscriptions'), ('travel', 'Travel & Holidays'), ('gifts', 'Gifts & Presents'), ('donations', 'Donations & Charity'), ('weddings', 'Weddings & Events'), ('taxes', 'Taxes'), ('insurance', 'Insurance'), ('salary', 'Salary & Wages'), ('business', 'Business Income'), ('freelance', 'Freelance & Side Hustle'), ('farm_sales', 'Farm Sales'), ('rental_income', 'Rental Income'), ('investment', 'Investment Returns'), ('savings', 'Savings')], max_length=100),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
